# Generated by Django 4.1.1 on 2022-09-15 00:59

import article.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_video_text_image_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=article.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
